let recipeData = [
  {
    title: "Grilled Cheese Sandwich",
    titleDescription:
      "This easy grilled cheese sandwich has a crispy Parmesan crust and a gooey Cheddar and bacon filling, and is simply the best I've ever had! As far as grilled cheese goes, this is it!",
    prepTime: "10 mins",
    cookingTime: "6 mins",
    totalTime: "16 mins",
    servings: "4",
    ingredients: [
      "¼ cup butter, softened",
      "1 cup freshly grated Parmigiano-Reggiano cheese",
      "8 slices cooked bacon",
      "8 slices sourdough bread",
      "4 slices Cheddar cheese",
    ],
    fat: "32g",
    calories: "510",
    carbs: "30g",
    protein: "27g",
    image: require("../assets/images/grilledcheesesandwich.webp"),
  },
  {
    title: "Old-Fashioned Potato Salad",
    titleDescription:
      "This potato salad recipe is for the traditional creamy type of potato salad, with eggs, celery, and relish. It's perfect for making ahead to let the flavors develop.",
    prepTime: "15 mins",
    cookingTime: "15 mins",
    totalTime: "1 hour",
    servings: "8",
    ingredients: [
      "5 medium potatoes",
      "3 large eggs",
      "1 cup chopped celery",
      "½ cup chopped onion",
      "½ cup sweet pickle relish",
      "¼ cup mayonnaise",
      "1 tablespoon prepared mustard",
      "¼ teaspoon garlic salt",
      "¼ teaspoon celery salt",
      "ground black pepper to taste",
    ],
    fat: "8g",
    calories: "206",
    carbs: "31g",
    protein: "6g",
    image: require("../assets/images/potato.webp"),
  },
  {
    title: "Texas Pulled Pork",
    titleDescription:
      "This Texas-style pulled pork recipe has a tangy barbeque sauce that's easy to make in the slow cooker. I like to serve the shredded pork on toasted buttered rolls. My family's favorite!",
    prepTime: "15 mins",
    cookingTime: "5 hours",
    totalTime: "5 hrs 15 mins",
    servings: "8",
    ingredients: [
      "1 teaspoon vegetable oil",
      "1 (4 pound) pork shoulder roast",
      "1 cup barbeque sauce",
      "½ cup apple cider vinegar",
      "½ cup chicken broth",
      "¼ cup light brown sugar",
      "1 tablespoon prepared yellow mustard",
      "1 tablespoon Worcestershire sauce",
      "1 tablespoon chili powder",
      "1 extra large onion, chopped",
      "2 large cloves garlic, crushed",
      "1 ½ teaspoons dried thyme",
      "8 hamburger buns, split",
      "2 tablespoons butter, or as needed",
    ],
    fat: "23g",
    calories: "528",
    carbs: "46g",
    protein: "32g",
    image: require("../assets/images/pulledPork.webp"),
  },
  {
    title: "Texas Pulled Pork",
    titleDescription:
      "This Texas-style pulled pork recipe has a tangy barbeque sauce that's easy to make in the slow cooker. I like to serve the shredded pork on toasted buttered rolls. My family's favorite!",
    prepTime: "15 mins",
    cookingTime: "5 hours",
    totalTime: "5 hrs 15 mins",
    servings: "8",
    ingredients: [
      "1 teaspoon vegetable oil",
      "1 (4 pound) pork shoulder roast",
      "1 cup barbeque sauce",
      "½ cup apple cider vinegar",
      "½ cup chicken broth",
      "¼ cup light brown sugar",
      "1 tablespoon prepared yellow mustard",
      "1 tablespoon Worcestershire sauce",
      "1 tablespoon chili powder",
      "1 extra large onion, chopped",
      "2 large cloves garlic, crushed",
      "1 ½ teaspoons dried thyme",
      "8 hamburger buns, split",
      "2 tablespoons butter, or as needed",
    ],
    fat: "23g",
    calories: "528",
    carbs: "46g",
    protein: "32g",
    image: require("../assets/images/pulledPork.webp"),
  },
  {
    title: "Texas Pulled Pork",
    titleDescription:
      "This Texas-style pulled pork recipe has a tangy barbeque sauce that's easy to make in the slow cooker. I like to serve the shredded pork on toasted buttered rolls. My family's favorite!",
    prepTime: "15 mins",
    cookingTime: "5 hours",
    totalTime: "5 hrs 15 mins",
    servings: "8",
    ingredients: [
      "1 teaspoon vegetable oil",
      "1 (4 pound) pork shoulder roast",
      "1 cup barbeque sauce",
      "½ cup apple cider vinegar",
      "½ cup chicken broth",
      "¼ cup light brown sugar",
      "1 tablespoon prepared yellow mustard",
      "1 tablespoon Worcestershire sauce",
      "1 tablespoon chili powder",
      "1 extra large onion, chopped",
      "2 large cloves garlic, crushed",
      "1 ½ teaspoons dried thyme",
      "8 hamburger buns, split",
      "2 tablespoons butter, or as needed",
    ],
    fat: "23g",
    calories: "528",
    carbs: "46g",
    protein: "32g",
    image: require("../assets/images/pulledPork.webp"),
  },
];

export { recipeData };
